[phases.setup]
nixPkgs = [
    "python311",
    "gcc"
]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /opt/venv/bin/activate && pip install --only-binary=all --no-cache-dir -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && python railway_ultimate_fix.py"

[variables]
PYTHONPATH = "/app:/opt/venv/lib/python3.11/site-packages"
FLASK_APP = "app.py"
FLASK_ENV = "production"
PIP_CACHE_DIR = "/tmp/pip-cache"
NPY_NUM_BUILD_JOBS = "1"
OPENBLAS_NUM_THREADS = "1"
OMP_NUM_THREADS = "1"