[build]
builder = "nixpacks"

[deploy]
startCommand = ". /opt/venv/bin/activate && python railway_simple.py"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app"
FLASK_APP = "app.py"
FLASK_ENV = "production"
PIP_CACHE_DIR = "/tmp/pip-cache"
# Updated: 2025-08-15 - Use complete app with proper dependency installation
