[build]
builder = "nixpacks"

[deploy]
startCommand = ". /opt/venv/bin/activate && gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app"
FLASK_APP = "app.py"
FLASK_ENV = "production"
# Updated: 2025-07-26 - Fixed 404 export errors with improved cleanup system
