[build]
builder = "nixpacks"

[deploy]
startCommand = ". /opt/venv/bin/activate && python app_fallback.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app"
FLASK_APP = "app_fallback.py"
FLASK_ENV = "production"
NUMPY_DISABLE_PYTHON_CHECKS = "1"
# Updated: 2025-07-26 - Using fallback app without numpy/pandas dependencies
